{% set name = "waf" %}
{% set version = "2.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/waf-project/waf/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 8810ac98f15f8111a8809a7fecae7dd4c66b4395359d9913a9ef573e3977eb28

build:
  number: 0
  script:
    - python waf-light --make-waf --tool=swig,cython,boost,use_config
    - cp waf "${PREFIX}/bin"     # [unix]
    - copy waf "%SCRIPTS%"   # [win]

requirements:
  build:
    - python

  run:
    - python

test:
  source_files:
    - wscript

  commands:
    - waf --help
    - waf configure
    - waf build

about:
  home: https://waf.io
  license: BSD 3-Clause
  summary: A build automation tool.

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - tarcisiofischer
    - dfroger
