{% set name = "waf" %}
{% set version = "2.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.py
  url: https://waf.io/{{ name }}-{{ version }}
  sha256: 5404fc1ab93813942f9c7b3d1d3470e05e52161deefcb7fdb807da95e90940cc

build:
  number: 0
  script:
    - cp {{name}}-{{version}}.py "${PREFIX}/bin/waf"  # [unix]

    - copy {{name}}-{{version}}.py "%SCRIPTS%/waf.py"  # [win]
    - copy "%RECIPE_DIR%\waf.bat" "%SCRIPTS%"  # [win]

requirements:
  build:
    - python

  run:
    - python

test:
  files:
    - wscript

  commands:
    - waf configure
    - waf build
    - waf --help

about:
  home: https://waf.io
  license: BSD 3-Clause
  summary: A build automation tool.

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - tarcisiofischer
    - dfroger
