{% set version = "2.0.27" %}


package:
  name: waf
  version: {{ version }}

source:
  url: https://waf.io/waf-{{ version }}.tar.bz2
  sha256: 0c15f1b20de823c4fd5a224e5b0158446ef0b30f8a2f2185ac2218eb67c94519

build:
  number: 0
  script:
    - python waf-light --make-waf --tool=swig,cython,boost,use_config
    - cp waf "${PREFIX}/bin"     # [unix]
    - copy waf "%SCRIPTS%"   # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python

  run:
    - python

test:
  files:
    - wscript

  commands:
    - waf --help
    - waf configure
    - waf build

about:
  home: https://waf.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: utils/launcher/LICENSE
  summary: A build automation tool.
  doc_url: https://waf.io/book/
  dev_url: https://gitlab.com/ita1024/waf

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - tarcisiofischer
    - dfroger
