# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fwk5FPLczY/6iJqeApQv3OaH9XJZm769Rqrho60p2p5WjKoXkWb1R7jpPPizKZFlcdHXfo8I5fQpvHWJDHXMczqv1Y0LuPsMsr6smgKZ5Pp85014AP0bFaPygmaATgsuVw69jVmJ3SJDu3uoA23OEm4nh2tycBCANfE2mpc0RHlDMuvlzC4rOF+Pn0jYIQfa1PmRamDXEJhFT06ahajmE0rkECgTvNDW2taRvYhspuCtf7Zd/e9Dl5S32QiyjTgauCVZeJozT3VqXVK3m/vvBRLZuCSr1zS+q/L/LYqVjaf2m+hLzvnDXAueUUmO1CWB4y2DNtIPS41QN8f8NCOSQiFhFwn2Au79ejFbejIR8EnUuV91NeIFyajJy4Kh4eVOjQSQI0/k1fBWAfXA1CkHnW/e1LvUlUIxnr9hHKckXNChhvQHOl+Se3z8nmbMjsU46DwbZYXTHXbW7a3I78kuzEM03FdNa7x6QV1HB7V2Ca2dLratsq+MrQzfqHoHeLnwgPfBAlDWDSCC0zaMMzoWy6UUOBdRvRYWYBGCrSOpGTCUzsYJKLHZX45o1wSJW2xogFBqkI2ygh9Npu0gAQsCL32tMZ7kQkz98cUewngriOi3Zv5OcgVmF9kykNq0EbJ9s5WtwE5bbLqn7uq4AFURQishh95ALaUXBu5iWoT3T44="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
